# Generated by Django 2.2.7 on 2019-11-10 16:59

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField(default=datetime.datetime(2019, 11, 10, 16, 59, 31, 461490, tzinfo=utc))),
                ('name', models.CharField(max_length=100)),
                ('mrp', models.FloatField(default=0.0)),
                ('discount', models.FloatField(default=0.0)),
                ('sale_price', models.FloatField(default=0.0)),
                ('available', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('categories', models.ManyToManyField(to='inventory.Category')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.ProductType'),
        ),
    ]
