# Generated by Django 2.2.7 on 2019-11-23 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='build',
            field=models.CharField(choices=[('spherical', 'Spherical'), ('toric', 'Toric')], default='spherical', max_length=10),
        ),
    ]
