# Generated by Django 2.2.7 on 2019-11-29 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_product_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Power',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='cyl_powers',
            field=models.ManyToManyField(related_name='cyl_powers', to='inventory.Power'),
        ),
        migrations.AddField(
            model_name='product',
            name='sph_powers',
            field=models.ManyToManyField(related_name='sph_powers', to='inventory.Power'),
        ),
    ]
