# Generated by Django 2.2.7 on 2019-12-05 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20191129_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cyl_powers',
            field=models.ManyToManyField(blank=True, null=True, related_name='cyl_powers', to='inventory.Power'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sph_powers',
            field=models.ManyToManyField(blank=True, null=True, related_name='sph_powers', to='inventory.Power'),
        ),
    ]
