# Generated by Django 2.2.7 on 2019-12-05 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_auto_20191205_1801'),
    ]

    operations = [
        migrations.CreateModel(
            name='Axis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('axis', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='axis',
            field=models.ManyToManyField(blank=True, to='inventory.Axis'),
        ),
    ]
