# Generated by Django 2.2.7 on 2019-11-13 14:07

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0003_product_manufacturer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2019, 11, 13, 14, 7, 46, 595041, tzinfo=utc))),
                ('sub_total', models.FloatField(default=0.0)),
                ('tax', models.FloatField(default=0.0)),
                ('shipping', models.FloatField(default=0.0)),
                ('discount', models.FloatField(default=0.0)),
                ('total', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('In Process', 'In Process'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered')], max_length=50)),
                ('courier', models.CharField(max_length=100)),
                ('tracking_number', models.CharField(max_length=100)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('products', models.ManyToManyField(to='inventory.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2019, 11, 13, 14, 7, 46, 596369, tzinfo=utc))),
                ('amount', models.FloatField(default=0.0)),
                ('mode', models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline')], max_length=30)),
                ('method', models.CharField(max_length=100)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='orders.Order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
