# Generated by Django 2.2.7 on 2019-12-08 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orderline_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='total',
            field=models.FloatField(default=0.0),
        ),
    ]
