# Generated by Django 2.2.7 on 2019-12-08 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_orderline_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
